/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Classes;

import Classes.*;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.Reader;
import java.io.StringReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Symbol;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author eecon
 */
public class minisql extends javax.swing.JFrame {

    String root;
    File file;
    //List<String> errors = new List<>();
    FileManager manager = new FileManager();

    /**
     * Creates new form minisql
     */
    public minisql() throws Exception {
        initComponents();
        startLexer();
        startCUP();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnSearchFile = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAFileContent = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtAnalyze = new javax.swing.JTextArea();
        jBtnAnalyze = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnSearchFile.setText("Buscar archivo");
        jBtnSearchFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSearchFileActionPerformed(evt);
            }
        });

        jTxtAFileContent.setEditable(false);
        jTxtAFileContent.setColumns(20);
        jTxtAFileContent.setRows(5);
        jScrollPane1.setViewportView(jTxtAFileContent);

        jLabel1.setText("Contenido de archivo");

        jTxtAnalyze.setEditable(false);
        jTxtAnalyze.setColumns(20);
        jTxtAnalyze.setRows(5);
        jScrollPane2.setViewportView(jTxtAnalyze);

        jBtnAnalyze.setText("Realizar analisis");
        jBtnAnalyze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAnalyzeActionPerformed(evt);
            }
        });

        jLabel2.setText("Analisis Sintacto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jBtnSearchFile, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(148, 148, 148))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBtnAnalyze, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAnalyze)
                    .addComponent(jBtnSearchFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSearchFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSearchFileActionPerformed
        // TODO add your handling code here:
        JFileChooser file_chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo de Texto", "txt");
        FileNameExtensionFilter filter2 = new FileNameExtensionFilter("Archivo SQL", "sql");
        file_chooser.addChoosableFileFilter(filter);
        file_chooser.addChoosableFileFilter(filter2);
        int value = file_chooser.showOpenDialog(this);
        if (value == JFileChooser.APPROVE_OPTION) {
            file = file_chooser.getSelectedFile();
            root = file.getPath();

            String text = "";
            try {
                text = manager.readFile(root);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(minisql.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (!text.isEmpty()) {
                jTxtAFileContent.setText(text);
                try {
                    lexicalAnalyzer();
                } catch (IOException ex) {
                    Logger.getLogger(minisql.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_jBtnSearchFileActionPerformed

    private void jBtnAnalyzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAnalyzeActionPerformed
        if (jTxtAFileContent.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Seleccione un archivo primero");
        } else {
            String Text = jTxtAFileContent.getText();
            Syntax s = new Syntax(new Classes.LexerCup(new StringReader(Text)));
            try {
                s.parse();
                jTxtAnalyze.setText("El archivo se analizo correctamente");
                jTxtAnalyze.setForeground(Color.BLACK);

            } catch (Exception ex) {
                String print_text = s.getErrorString();
                jTxtAnalyze.setText("El archivo contiene errores");
                jTxtAnalyze.setText(print_text);
                jTxtAnalyze.setForeground(Color.red);
            }
        }
    }//GEN-LAST:event_jBtnAnalyzeActionPerformed

    public static void saveError(String e) {

    }

    public void startLexer() {
        String absolutePath = new File(".").getAbsolutePath();
        absolutePath = absolutePath.substring(0, absolutePath.length() - 1);
        absolutePath += "src\\Classes\\Lexer.flex";
        File lexerFile = new File(absolutePath);
        jflex.Main.generate(lexerFile);
    }

    public void startCUP() throws IOException, Exception {
        String syntaxRoute = "", aux = "";
        String absolutePath = new File(".").getAbsolutePath();
        absolutePath = absolutePath.substring(0, absolutePath.length() - 1);
        syntaxRoute = absolutePath;
        aux = absolutePath;
        absolutePath += "src\\Classes\\LexerCup.flex";
        syntaxRoute += "src\\Classes\\Syntax.cup";
        String[] routesS = {"-parser", "Syntax", syntaxRoute};

        File file = new File(absolutePath);
        jflex.Main.generate(file);
        java_cup.Main.main(routesS);

        Path symRoute_aux = Paths.get(aux + "/src/Classes/sym.java");
        Path symRoute = Paths.get(aux + "/sym.java");
        Files.deleteIfExists(symRoute_aux);
        Files.move(symRoute, symRoute_aux);

        Path sinRoute_aux = Paths.get(aux + "/src/Classes/Syntax.java");
        Path sinRoute = Paths.get(aux + "/Syntax.java");
        Files.deleteIfExists(sinRoute_aux);
        Files.move(sinRoute, sinRoute_aux);

    }

    public void lexicalAnalyzer() throws IOException {
        validateTokens();
        String file_name = file.getName();
        String aux_root = root.substring(0, root.length() - file_name.length());
        file_name = file_name.substring(0, file_name.length() - 4);
        manager.writeFile(file_name, jTxtAnalyze.getText(), root, aux_root, "out");
        JOptionPane.showMessageDialog(null, "El archivo " + file_name + " .out se escribió en\nla ubicación del archivo original");
    }

    public void validateTokens() throws FileNotFoundException, IOException {
        Reader reader = new BufferedReader(new FileReader(file));

        Lexer lexer = new Lexer(reader);
        String resultado = "";
        while (true) {
            Token token = lexer.yylex();
            if (token == null) {
                //jTxtAnalyze.setText(resultado);
                break;
            }
            switch (token) {
                case ERROR:
                    resultado += "Error caracter invalido, " + lexer.lexeme + "  Line: " + (lexer.getLine() + 1) + "   PrimeraColumna: " + lexer.getColumn() + "   UltimaColumna: " + (lexer.getColumn() + lexer.lexeme.length()) + "\n";
                    break;
                case ERROR_F:
                    resultado += "Error float invalido, " + lexer.lexeme + "  Line: " + (lexer.getLine() + 1) + "   PrimeraColumna: " + lexer.getColumn() + "   UltimaColumna: " + (lexer.getColumn() + lexer.lexeme.length()) + "\n";
                    break;
                case ID:
                    String string = "";
                    if (lexer.lexeme.length() > 31) {
                        string = lexer.lexeme.substring(0, 31);
                        resultado += "Error de truncado, " + token + " " + string + "  Line: " + (lexer.getLine() + 1) + "   FirstCol: " + lexer.getColumn() + "   LastCol: " + (lexer.getColumn() + lexer.lexeme.length()) + "\n";
                    } else {
                        resultado += "TOKEN: " + token + " " + lexer.lexeme + "  Line: " + (lexer.getLine() + 1) + "   FirstCol: " + lexer.getColumn() + "   LastCol: " + (lexer.getColumn() + lexer.lexeme.length()) + "\n";
                    }
                    break;
                case COMENTARIO_M:
                    resultado += "Error, comentario multilinea " + token + "  Line: " + (lexer.getLine() + 1) + "   FirstCol: " + lexer.getColumn() + "   LastCol: " + (lexer.getColumn() + lexer.lexeme.length()) + "\n";
                    int firstNewLinePosition = 0;
                    for (int i = 0; i < lexer.lexeme.length(); i++) {
                        if (lexer.lexeme.charAt(i) == '\n') {
                            firstNewLinePosition = i;
                            break;
                        }
                    }

                    if (firstNewLinePosition != 0) {
                        lexer.yypushback(lexer.lexeme.length() - firstNewLinePosition);
                    }
                    break;
                default:
                    resultado += "TOKEN: " + token + "  Line: " + (lexer.getLine() + 1) + "   FirstCol: " + lexer.getColumn() + "   LastCol: " + (lexer.getColumn() + lexer.lexeme.length()) + "\n";
                    break;
            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(minisql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(minisql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(minisql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(minisql.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new minisql().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(minisql.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAnalyze;
    private javax.swing.JButton jBtnSearchFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTxtAFileContent;
    private javax.swing.JTextArea jTxtAnalyze;
    // End of variables declaration//GEN-END:variables
}
