
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Oct 27 09:28:52 CST 2019
//----------------------------------------------------

package Classes;

import java_cup.runtime.Symbol;

/** CUP v0.10k generated parser.
  * @version Sun Oct 27 09:28:52 CST 2019
  */
public class Syntax
 extends java_cup.runtime.lr_parser
{
  /** Default constructor. */
  public Syntax() {super();}

  /** Constructor which sets the default scanner. */
  public Syntax(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\053\000\002\002\004\000\002\003\003\000\002\004" +
    "\005\000\002\004\002\000\002\005\003\000\002\005\003" +
    "\000\002\005\003\000\002\005\003\000\002\007\003\000" +
    "\002\007\003\000\002\007\003\000\002\007\003\000\002" +
    "\010\003\000\002\010\003\000\002\010\003\000\002\010" +
    "\003\000\002\012\003\000\002\006\003\000\002\006\003" +
    "\000\002\006\004\000\002\006\004\000\002\006\005\000" +
    "\002\024\004\000\002\025\005\000\002\025\002\000\002" +
    "\026\004\000\002\026\002\000\002\027\003\000\002\027" +
    "\003\000\002\027\003\000\002\027\003\000\002\030\004" +
    "\000\002\031\004\000\002\031\004\000\002\031\002\000" +
    "\002\032\004\000\002\033\004\000\002\033\004\000\002" +
    "\033\002\000\002\034\005\000\002\034\003\000\002\034" +
    "\003\000\002\034\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\031\000\004\002\ufffe\001\002\000\004\002\000\001" +
    "\002\000\006\033\ufff2\141\ufff2\001\002\000\006\033\ufff7" +
    "\141\ufff7\001\002\000\006\033\ufffb\141\ufffb\001\002\000" +
    "\006\033\ufff5\141\ufff5\001\002\000\006\033\ufffd\141\ufffd" +
    "\001\002\000\006\033\ufff4\141\ufff4\001\002\000\006\033" +
    "\ufffc\141\ufffc\001\002\000\006\033\025\141\026\001\002" +
    "\000\006\033\ufff3\141\ufff3\001\002\000\006\033\ufff9\141" +
    "\ufff9\001\002\000\004\002\024\001\002\000\006\033\ufff8" +
    "\141\ufff8\001\002\000\006\033\ufff1\141\ufff1\001\002\000" +
    "\006\033\ufffa\141\ufffa\001\002\000\006\033\ufff6\141\ufff6" +
    "\001\002\000\004\002\001\001\002\000\006\002\uffef\141" +
    "\032\001\002\000\006\002\ufff0\033\031\001\002\000\004" +
    "\002\ufffe\001\002\000\004\002\uffff\001\002\000\004\002" +
    "\uffed\001\002\000\006\002\uffee\033\033\001\002\000\004" +
    "\002\uffec\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\031\000\042\003\016\004\003\005\013\007\010\010" +
    "\012\011\006\012\021\013\015\014\017\015\005\016\022" +
    "\017\007\020\011\021\014\022\004\023\020\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\006\026\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\040\004\027\005\013\007\010\010\012\011\006\012\021" +
    "\013\015\014\017\015\005\016\022\017\007\020\011\021" +
    "\014\022\004\023\020\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Syntax$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Syntax$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Syntax$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private Symbol s;

    public void syntax_error(Symbol s){
        this.s = s;
    }

    public Symbol getS(){
        return this.s;
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Syntax$actions {
  private final Syntax parser;

  /** Constructor */
  CUP$Syntax$actions(Syntax parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Syntax$do_action(
    int                        CUP$Syntax$act_num,
    java_cup.runtime.lr_parser CUP$Syntax$parser,
    java.util.Stack            CUP$Syntax$stack,
    int                        CUP$Syntax$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Syntax$result;

      /* select the action based on the action number */
      switch (CUP$Syntax$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // parte2 ::= obj_n 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(26/*parte2*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // parte2 ::= FLOAT 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(26/*parte2*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // parte2 ::= INT 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(26/*parte2*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // parte2 ::= PARENTESIS_ABIERTO aritmetica PARENTESIS_CERRADO 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(26/*parte2*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-2)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // parte1 ::= 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(25/*parte1*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // parte1 ::= DIV parte2 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(25/*parte1*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-1)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // parte1 ::= MULT parte2 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(25/*parte1*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-1)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // parte ::= parte2 parte1 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(24/*parte*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-1)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // aritmetica1 ::= 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(23/*aritmetica1*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // aritmetica1 ::= MENOS parte 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(23/*aritmetica1*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-1)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // aritmetica1 ::= MAS parte 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(23/*aritmetica1*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-1)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // aritmetica ::= parte aritmetica1 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(22/*aritmetica*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-1)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // tipo_dato ::= FLOAT 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(21/*tipo_dato*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // tipo_dato ::= INT 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(21/*tipo_dato*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // tipo_dato ::= BIT 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(21/*tipo_dato*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // tipo_dato ::= STRING 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(21/*tipo_dato*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // obj_n2 ::= 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(20/*obj_n2*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // obj_n2 ::= PUNTO ID 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(20/*obj_n2*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-1)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // obj_n1 ::= 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(19/*obj_n1*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // obj_n1 ::= PUNTO ID obj_n2 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(19/*obj_n1*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-2)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // obj_n ::= ID obj_n1 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(18/*obj_n*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-1)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // EndStmt ::= PUNTO_COMA GO PUNTO_COMA 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(4/*EndStmt*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-2)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // EndStmt ::= GO PUNTO_COMA 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(4/*EndStmt*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-1)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // EndStmt ::= PUNTO_COMA GO 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(4/*EndStmt*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-1)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // EndStmt ::= PUNTO_COMA 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(4/*EndStmt*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // EndStmt ::= GO 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(4/*EndStmt*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // StmtTSQL ::= cursor 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(8/*StmtTSQL*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // StmtDDL ::= drop 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(6/*StmtDDL*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // StmtDDL ::= truncate 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(6/*StmtDDL*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // StmtDDL ::= alter 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(6/*StmtDDL*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // StmtDDL ::= create 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(6/*StmtDDL*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // StmtDML ::= delete 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(5/*StmtDML*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // StmtDML ::= update 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(5/*StmtDML*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // StmtDML ::= insert 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(5/*StmtDML*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // StmtDML ::= select 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(5/*StmtDML*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Stmt ::= StmtTSQL 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(3/*Stmt*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Stmt ::= StmtTCL 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(3/*Stmt*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Stmt ::= StmtDDL 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(3/*Stmt*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // Stmt ::= StmtDML 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(3/*Stmt*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // general ::= 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(2/*general*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // general ::= Stmt EndStmt general 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(2/*general*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-2)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // Start ::= general 
            {
              Object RESULT = null;

              CUP$Syntax$result = new java_cup.runtime.Symbol(1/*Start*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          return CUP$Syntax$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= Start EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Syntax$stack.elementAt(CUP$Syntax$top-1)).value;
		RESULT = start_val;
              CUP$Syntax$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-1)).left, ((java_cup.runtime.Symbol)CUP$Syntax$stack.elementAt(CUP$Syntax$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$Syntax$parser.done_parsing();
          return CUP$Syntax$result;

          default:
            {
              throw new Exception(
                 "Invalid action number found in internal parse table");
            }

        }
    }
}

